<a href="https://colab.research.google.com/github/valid999/NLP_Models/blob/main/Sentence_Transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Senctence Transformers

**Sentence Embedding**

**Sentence Similarity**

**Semantic search**

**Clustring**

In [2]:
!pip install -U sentence-transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.5/156.5 kB 3.4 MB/s eta 0:00:00


# Generating Embedding

In [5]:
from sentence_transformers import SentenceTransformer , util
model = SentenceTransformer('all-MiniLM-L6-v2')

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()


tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [7]:
sentences = ['This framework generates embeddings for each input sentence' , 'Sentences are passed as a list of string.']
embeddings = model.encode(sentences)

for sentence , embedding in zip(sentences , embeddings):
  print("Sentence:" , sentence)
  print("EMbedding:" , embedding)
  print("")
  print(len(embedding))

Sentence: This framework generates embeddings for each input sentence
EMbedding: [-1.37173552e-02 -4.28515449e-02 -1.56286024e-02  1.40537303e-02
  3.95537727e-02  1.21796280e-01  2.94334106e-02 -3.17524187e-02
  3.54959629e-02 -7.93139935e-02  1.75878741e-02 -4.04369719e-02
  4.97259349e-02  2.54912246e-02 -7.18700588e-02  8.14968869e-02
  1.47069141e-03  4.79626991e-02 -4.50336412e-02 -9.92174670e-02
 -2.81769745e-02  6.45046085e-02  4.44670543e-02 -4.76217009e-02
 -3.52952331e-02  4.38671783e-02 -5.28566055e-02  4.33063833e-04
  1.01921506e-01  1.64072234e-02  3.26996595e-02 -3.45986746e-02
  1.21339476e-02  7.94870779e-02  4.58345609e-03  1.57777797e-02
 -9.68206208e-03  2.87625659e-02 -5.05805984e-02 -1.55793717e-02
 -2.87906546e-02 -9.62280575e-03  3.15556750e-02  2.27349028e-02
  8.71449187e-02 -3.85027491e-02 -8.84718448e-02 -8.75498448e-03
 -2.12343335e-02  2.08923239e-02 -9.02077407e-02 -5.25732562e-02
 -1.05638904e-02  2.88310610e-02 -1.61455162e-02  6.17837207e-03
 -1.23234

# Cosine-Similarity

In [8]:
emb1 = model.encode("I am eating Apple")
emb2 = model.encode("I Like fruits")

cos_sim = util.cos_sim(emb1 , emb2)
print("Cosine-Similarity:" , cos_sim)

Cosine-Similarity: tensor([[0.5398]])


# Compute the Cosine Similarity between all pairs

In [10]:
# Compute the cosine similarity between all pairs

sentences = ['A man is eating food',
             'A man is eating a piece of bread',
             'The girl is carrying a baby',
             'A man  is riding a horse' ,
             'A woman is playing violin',
             'A two men pushed carts through the woods' ,
             'A monkey is playing drums',
             'Somweone in gorilla costume is playing a set of drums']


# Encode all sentences
embeddings = model.encode(sentences)

# Compute the cosine similarity between all pairs
cos_sim = util.cos_sim(embeddings , embeddings)
cos_sim

tensor([[ 1.0000,  0.7379, -0.1136,  0.2450, -0.0741, -0.0171,  0.0453, -0.0108],
        [ 0.7379,  1.0000, -0.0666,  0.1383, -0.0833,  0.0020,  0.0386, -0.0370],
        [-0.1136, -0.0666,  1.0000, -0.1058,  0.0207, -0.0311,  0.0253, -0.0032],
        [ 0.2450,  0.1383, -0.1058,  1.0000, -0.0308,  0.0554,  0.0786,  0.1150],
        [-0.0741, -0.0833,  0.0207, -0.0308,  1.0000, -0.1496,  0.1957,  0.1694],
        [-0.0171,  0.0020, -0.0311,  0.0554, -0.1496,  1.0000, -0.0239, -0.0495],
        [ 0.0453,  0.0386,  0.0253,  0.0786,  0.1957, -0.0239,  1.0000,  0.4719],
        [-0.0108, -0.0370, -0.0032,  0.1150,  0.1694, -0.0495,  0.4719,  1.0000]])

In [11]:
# Add all pairs to a list with their cosine similarity score
all_sentence_combinations = []
for i in range(len(cos_sim)-1):
  for j in range(i+1 , len(cos_sim)):
    all_sentence_combinations.append((cos_sim[i][j] , i , j))
all_sentence_combinations

[(tensor(0.7379), 0, 1),
 (tensor(-0.1136), 0, 2),
 (tensor(0.2450), 0, 3),
 (tensor(-0.0741), 0, 4),
 (tensor(-0.0171), 0, 5),
 (tensor(0.0453), 0, 6),
 (tensor(-0.0108), 0, 7),
 (tensor(-0.0666), 1, 2),
 (tensor(0.1383), 1, 3),
 (tensor(-0.0833), 1, 4),
 (tensor(0.0020), 1, 5),
 (tensor(0.0386), 1, 6),
 (tensor(-0.0370), 1, 7),
 (tensor(-0.1058), 2, 3),
 (tensor(0.0207), 2, 4),
 (tensor(-0.0311), 2, 5),
 (tensor(0.0253), 2, 6),
 (tensor(-0.0032), 2, 7),
 (tensor(-0.0308), 3, 4),
 (tensor(0.0554), 3, 5),
 (tensor(0.0786), 3, 6),
 (tensor(0.1150), 3, 7),
 (tensor(-0.1496), 4, 5),
 (tensor(0.1957), 4, 6),
 (tensor(0.1694), 4, 7),
 (tensor(-0.0239), 5, 6),
 (tensor(-0.0495), 5, 7),
 (tensor(0.4719), 6, 7)]

In [12]:
# Sort list by the highest cosine similarity score
all_sentence_combinations = sorted(all_sentence_combinations, key=lambda x: x[0] , reverse=True)

print("Top-5 most similar pairs:")
for score , i , j in all_sentence_combinations[0:5]:
  print("{} \t {} \t {:.4f}".format(sentences[i] , sentences[j] , cos_sim[i][j]))

Top-5 most similar pairs:
A man is eating food 	 A man is eating a piece of bread 	 0.7379
A monkey is playing drums 	 Somweone in gorilla costume is playing a set of drums 	 0.4719
A man is eating food 	 A man  is riding a horse 	 0.2450
A woman is playing violin 	 A monkey is playing drums 	 0.1957
A woman is playing violin 	 Somweone in gorilla costume is playing a set of drums 	 0.1694


# Semantic Search

In [14]:
from sentence_transformers import SentenceTransformer , util
model = SentenceTransformer('clips/mfaq')

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/117 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.74k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/778 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py:365: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(


pytorch_model.bin:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/464 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/294 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [16]:
# Semantic search with NLP question and answering

question = "How many models can I host on HuggingFace"
answer_1 = "All plans come with unlimited private models and datasets"
answer_2 = "AutoNLP is an automatic way to train and deploy state-of-the-art NLP models , seamlessly"
answer_3 = "Based on how much training data and model variants are created , we send you a compute cosine "


query_embedding = model.encode(question)
corpus_embedding = model.encode([answer_1 , answer_2 , answer_3])


print(util.semantic_search(query_embedding , corpus_embedding))

[[{'corpus_id': 0, 'score': 0.6575074791908264}, {'corpus_id': 2, 'score': 0.6235505938529968}, {'corpus_id': 1, 'score': 0.5660152435302734}]]


In [17]:
from transformers import pipeline

In [20]:
qa_model = pipeline("question-answering")
question = "How many models can i host on HuggingFace"
context = "All plans come with unlimited private models and datasets"
qa_model(question = question , context = context)

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


{'score': 0.553877592086792, 'start': 20, 'end': 29, 'answer': 'unlimited'}

In [22]:
print(util.semantic_search(query_embedding  , corpus_embedding))

[[{'corpus_id': 0, 'score': 0.6575074791908264}, {'corpus_id': 2, 'score': 0.6235505938529968}, {'corpus_id': 1, 'score': 0.5660152435302734}]]


# Clustering

In [26]:
from sklearn.cluster import KMeans
import numpy as np

embedder = SentenceTransformer('all-MiniLM-L6-v2')


# Corpus with example sentences
corpus = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'Horse is eating grass.',
          'A man is eating pasta.',
          'A Woman is eating Biryani.',
          'The girl is carrying a baby.',
          'The baby is carried by the woman',
          'A man is riding a horse.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.',
          'A cheetah is running behind its prey.',
          'A cheetah chases prey on across a field.',
          'The cheetah is chasing a man who is riding the horse.',
          'man and women with their baby are watching cheetah in zoo'
          ]

corpus_embeddings = embedder.encode(corpus)

# Normalize the embeddings to unit length
corpus_embeddings = corpus_embeddings / np.linalg.norm(corpus_embeddings , axis = 1 , keepdims = True)

In [27]:
corpus_embeddings[0]

array([ 3.32415923e-02,  4.40611131e-03, -6.27698097e-03,  4.83787395e-02,
       -1.38702288e-01, -3.36174108e-02,  1.01128370e-01, -5.43849692e-02,
       -4.32477817e-02, -3.99411246e-02,  7.78633682e-03, -1.27489287e-02,
       -6.68302402e-02, -1.73865426e-02,  4.74506281e-02, -5.77242412e-02,
        1.01888366e-01, -9.11662937e-04,  8.22615027e-02, -5.03415726e-02,
        6.77302927e-02,  4.08765152e-02, -3.58018912e-02, -1.00682415e-01,
       -6.69354713e-03, -5.31686284e-02,  1.00335158e-01, -5.46135865e-02,
       -2.28481367e-02,  1.38387140e-02,  7.48658478e-02, -6.17880039e-02,
        6.39215931e-02,  1.62387323e-02, -5.32299615e-02, -3.86084318e-02,
        3.15275863e-02, -8.11529905e-02, -3.31432372e-02, -5.38505905e-04,
       -3.96069745e-03, -1.52734164e-02, -9.86421946e-04,  9.57987979e-02,
       -5.42920306e-02,  1.84572097e-02, -1.07143618e-01,  1.38884904e-02,
        3.94072384e-02, -2.69243568e-02, -9.15988758e-02, -1.14195142e-02,
        3.38137113e-02, -

In [36]:
clustring_model = KMeans(n_clusters = 4)
clustring_model.fit(corpus_embeddings)
cluster_assignment = clustring_model.labels_
print(cluster_assignment)

[3 3 0 3 3 1 1 0 0 2 2 0 0 0 1]


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [37]:
clustered_sentences = {}
for sentence_id , cluster_id in enumerate(cluster_assignment):
  if cluster_id not in clustered_sentences:
    clustered_sentences[cluster_id] = []

  clustered_sentences[cluster_id].append(corpus[sentence_id])
clustered_sentences

{3: ['A man is eating food.',
  'A man is eating a piece of bread.',
  'A man is eating pasta.',
  'A Woman is eating Biryani.'],
 0: ['Horse is eating grass.',
  'A man is riding a horse.',
  'A man is riding a white horse on an enclosed ground.',
  'A cheetah is running behind its prey.',
  'A cheetah chases prey on across a field.',
  'The cheetah is chasing a man who is riding the horse.'],
 1: ['The girl is carrying a baby.',
  'The baby is carried by the woman',
  'man and women with their baby are watching cheetah in zoo'],
 2: ['A monkey is playing drums.',
  'Someone in a gorilla costume is playing a set of drums.']}

In [38]:
clustered_sentences = {}
for sentence_id , cluster_id in enumerate(cluster_assignment):
  if cluster_id not in clustered_sentences:
    clustered_sentences[cluster_id] = []

  clustered_sentences[cluster_id].append(corpus[sentence_id])
clustered_sentences

{3: ['A man is eating food.',
  'A man is eating a piece of bread.',
  'A man is eating pasta.',
  'A Woman is eating Biryani.'],
 0: ['Horse is eating grass.',
  'A man is riding a horse.',
  'A man is riding a white horse on an enclosed ground.',
  'A cheetah is running behind its prey.',
  'A cheetah chases prey on across a field.',
  'The cheetah is chasing a man who is riding the horse.'],
 1: ['The girl is carrying a baby.',
  'The baby is carried by the woman',
  'man and women with their baby are watching cheetah in zoo'],
 2: ['A monkey is playing drums.',
  'Someone in a gorilla costume is playing a set of drums.']}